collections:
  recipes:
    output: true
defaults:
  - scope:
      path: "recipes" # an empty string here means all files in the project
      collection: recipes # previously `post` in Jekyll 2.2.
    values:
      layout: default
      is_recipe: true # automatically set is_recipe=true for all recipes
      is_post: true # automatically set is_post=true for all posts
      image: https://cloud.githubusercontent.com/assets/7868635/11022383/86fcdc7a-865d-11e5-9bee-4f61dc7a9a85.png
